Feature: LiveCodeBench/atcoder/hard — Snowflake Tree
  Complexity: T3
  Category: code/generation
  Mode: multi-turn

  Background:
    Given the following project files:
      """
      === problem.txt ===
      A "Snowflake Tree" is defined as a tree that can be generated by the following procedure:

      - Choose positive integers x,y.
      - Prepare one vertex.
      - Prepare x more vertices, and connect each of them to the vertex prepared in step 2.
      - For each of the x vertices prepared in step 3, attach y leaves to it.

      The figure below shows a Snowflake Tree with x=4,y=2. The vertices prepared in steps 2, 3, 4 are shown in red, blue, and green, respectively.

      You are given a tree T with N vertices. The vertices are numbered 1 to N, and the i-th edge (i=1,2,\dots,N-1) connects vertices u_i and v_i.
      Consider deleting zero or more vertices of T and the edges adjacent to them so that the remaining graph becomes a single Snowflake Tree. Find the minimum number of vertices that must be deleted. Under the constraints of this problem, it is always possible to transform T into a Snowflake Tree.

      Input

      The input is given from Standard Input in the following format:
      N
      u_1 v_1
      u_2 v_2
      \vdots
      u_{N-1} v_{N-1}

      Output

      Print the answer.

      Constraints


      - 3 \leq N \leq 3 \times 10^5
      - 1 \leq u_i < v_i \leq N
      - The given graph is a tree.
      - All input values are integers.

      Sample Input 1

      8
      1 3
      2 3
      3 4
      4 5
      5 6
      5 7
      4 8

      Sample Output 1

      1

      By deleting vertex 8, the given tree can be transformed into a Snowflake Tree with x=2,y=2.

      Sample Input 2

      3
      1 2
      2 3

      Sample Output 2

      0

      The given tree is already a Snowflake Tree with x=1,y=1.

      Sample Input 3

      10
      1 3
      1 2
      5 7
      6 10
      2 8
      1 6
      8 9
      2 7
      1 4

      Sample Output 3

      3

      === solution.py ===
      import sys

      # Read from stdin, write to stdout

      === test_solution.py ===
      import subprocess
      import sys

      TEST_CASES = [
          [
              "8\n1 3\n2 3\n3 4\n4 5\n5 6\n5 7\n4 8",
              "1"
          ],
          [
              "3\n1 2\n2 3",
              "0"
          ],
          [
              "10\n1 3\n1 2\n5 7\n6 10\n2 8\n1 6\n8 9\n2 7\n1 4",
              "3"
          ]
      ]


      def test_lcb():
          for i, (inp, expected) in enumerate(TEST_CASES):
              r = subprocess.run(
                  [sys.executable, "solution.py"],
                  input=inp,
                  capture_output=True,
                  text=True,
                  timeout=10,
              )
              assert r.returncode == 0, f"Case {i}: runtime error\n{r.stderr[:400]}"
              assert r.stdout.strip() == expected.strip(), (
                  f"Case {i}: expected {expected!r}, got {r.stdout!r}"
              )

      """

  Scenario: Agent solves the LiveCodeBench problem so all tests pass
    Given an agent is tasked with reading problem.txt and implementing solution.py so all pytest tests pass
    When the agent completes the task in the sandbox
    Then pytest exits with code 0
