Feature: LiveCodeBench/leetcode/hard — lexicographically-smallest-generated-string
  Complexity: T3
  Category: code/generation
  Mode: multi-turn

  Background:
    Given the following project files:
      """
      === problem.txt ===
      You are given two strings, str1 and str2, of lengths n and m, respectively.
      A string word of length n + m - 1 is defined to be generated by str1 and str2 if it satisfies the following conditions for each index 0 <= i <= n - 1:

      If str1[i] == 'T', the substring of word with size m starting at index i is equal to str2, i.e., word[i..(i + m - 1)] == str2.
      If str1[i] == 'F', the substring of word with size m starting at index i is not equal to str2, i.e., word[i..(i + m - 1)] != str2.

      Return the lexicographically smallest possible string that can be generated by str1 and str2. If no string can be generated, return an empty string "".
 
      Example 1:

      Input: str1 = "TFTF", str2 = "ab"
      Output: "ababa"
      Explanation:
      The table below represents the string "ababa"



      Index
      T/F
      Substring of length m


      0
      'T'
      "ab"


      1
      'F'
      "ba"


      2
      'T'
      "ab"


      3
      'F'
      "ba"



      The strings "ababa" and "ababb" can be generated by str1 and str2.
      Return "ababa" since it is the lexicographically smaller string.

      Example 2:

      Input: str1 = "TFTF", str2 = "abc"
      Output: ""
      Explanation:
      No string that satisfies the conditions can be generated.

      Example 3:

      Input: str1 = "F", str2 = "d"
      Output: "a"

 
      Constraints:

      1 <= n == str1.length <= 10^4
      1 <= m == str2.length <= 500
      str1 consists only of 'T' or 'F'.
      str2 consists only of lowercase English characters.

      === solution.py ===
      import sys

      # Read from stdin, write to stdout

      === test_solution.py ===
      import subprocess
      import sys

      TEST_CASES = [
          [
              "\"TFTF\"\n\"ab\"",
              "\"ababa\""
          ],
          [
              "\"TFTF\"\n\"abc\"",
              "\"\""
          ],
          [
              "\"F\"\n\"d\"",
              "\"a\""
          ]
      ]


      def test_lcb():
          for i, (inp, expected) in enumerate(TEST_CASES):
              r = subprocess.run(
                  [sys.executable, "solution.py"],
                  input=inp,
                  capture_output=True,
                  text=True,
                  timeout=10,
              )
              assert r.returncode == 0, f"Case {i}: runtime error\n{r.stderr[:400]}"
              assert r.stdout.strip() == expected.strip(), (
                  f"Case {i}: expected {expected!r}, got {r.stdout!r}"
              )

      """

  Scenario: Agent solves the LiveCodeBench problem so all tests pass
    Given an agent is tasked with reading problem.txt and implementing solution.py so all pytest tests pass
    When the agent completes the task in the sandbox
    Then pytest exits with code 0
